<?php session_start(); ?>
<?php
$web_frountend = array("html", "css", "bootstrap", "javascript", "jquery", "ajax");
$web_backend = array("php", "python", "rubyonrails", "nodejs");
$android_app = array("java", "kotlin", "reactnative");
$ios_app = array("objectivec", "swift");
$game_development = array("unity", "unreal", "godotengine", "cryengine", "c", "cpp", "c++", "c#");
$desktop_application = array("c#", "java", "python");
$btier1 = array("iitkharagpur", "iitkgp",  "iitbombay", "iitmumbai", "iitb", "iitkanpur", "iitk", "iitmadras", "iitm", "iitdelhi", "iitd", "iitguwahati", "iitguvahati", "iitg", "iitroorkee", "iitroorki", "iitr", "iitvaranasi", "iitbhu", "iitbhubaneshwar", "iitgandhinagar", "iithyderabad", "iitjodhpur", "iitpatna", "iitropar", "iitroper", "iitindore", "iitmandi", "iitpalakkad", "iitpalakad", "iittirupati", "iitdhanbad", "iitbhilai", "iitgoa", "iitjammu", "iitjammuandkashmir", "iitdharwad", "iitdharvad", "indianinstituteoftechnologykharagpur", "indianinstituteoftechnologybombay", "indianinstituteoftechnologymumbai", "iitb", "indianinstituteoftechnologykanpur", "iitk", "indianinstituteoftechnologymadras", "iitm", "indianinstituteoftechnologydelhi", "iitd", "indianinstituteoftechnologyguwahati", "indianinstituteoftechnologyguvahati", "iitg", "indianinstituteoftechnologyroorkee", "indianinstituteoftechnologyroorki", "iitr", "indianinstituteoftechnologyvaranasi", "iitbhu", "indianinstituteoftechnologybhubaneshwar", "indianinstituteoftechnologygandhinagar", "indianinstituteoftechnologyhyderabad", "indianinstituteoftechnologyjodhpur", "indianinstituteoftechnologypatna", "indianinstituteoftechnologyropar", "indianinstituteoftechnologyroper", "indianinstituteoftechnologyindore", "indianinstituteoftechnologymandi", "indianinstituteoftechnologypalakkad", "indianinstituteoftechnologypalakad", "indianinstituteoftechnologytirupati", "indianinstituteoftechnologydhanbad", "indianinstituteoftechnologybhilai", "indianinstituteoftechnologygoa", "indianinstituteoftechnologyjammu", "indianinstituteoftechnologyjammuandkashmir", "indianinstituteoftechnologydharwad", "indianinstituteoftechnologydharvad", "nitwarangal", "nitvarangal", "nittrichy", "nitsurathkal", "nitsuratkal", "nitallahbad", "nitallahabad", "nitbhopal", "nitcalicut", "nitjaipur", "nitnagpur", "vnit", "nitsurat", "nationalinstituteoftechnologywarangal", "nationalinstituteoftechnologyvarangal", "nationalinstituteoftechnologytrichy", "nationalinstituteoftechnologysurathkal", "nationalinstituteoftechnologysuratkal", "nationalinstituteoftechnologyallahbad", "nationalinstituteoftechnologyallahabad", "nationalinstituteoftechnologybhopal", "nationalinstituteoftechnologycalicut", "nationalinstituteoftechnologyjaipur", "nationalinstituteoftechnologynagpur", "nationalinstituteoftechnologysurat");

$mtier1 = array("iitkharagpur", "iitkgp",  "iitbombay", "iitmumbai", "iitb", "iitkanpur", "iitk", "iitmadras", "iitm", "iitdelhi", "iitd", "iitguwahati", "iitguvahati", "iitg", "iitroorkee", "iitroorki", "iitr", "iitvaranasi", "iitbhu", "iitbhubaneshwar", "iitgandhinagar", "iithyderabad", "iitjodhpur", "iitpatna", "iitropar", "iitroper", "iitindore", "iitmandi", "iitpalakkad", "iitpalakad", "iittirupati", "iitdhanbad", "iitbhilai", "iitgoa", "iitjammu", "iitjammuandkashmir", "iitdharwad", "iitdharvad", "indianinstituteoftechnologykharagpur", "indianinstituteoftechnologybombay", "indianinstituteoftechnologymumbai", "iitb", "indianinstituteoftechnologykanpur", "iitk", "indianinstituteoftechnologymadras", "iitm", "indianinstituteoftechnologydelhi", "iitd", "indianinstituteoftechnologyguwahati", "indianinstituteoftechnologyguvahati", "iitg", "indianinstituteoftechnologyroorkee", "indianinstituteoftechnologyroorki", "iitr", "indianinstituteoftechnologyvaranasi", "iitbhu", "indianinstituteoftechnologybhubaneshwar", "indianinstituteoftechnologygandhinagar", "indianinstituteoftechnologyhyderabad", "indianinstituteoftechnologyjodhpur", "indianinstituteoftechnologypatna", "indianinstituteoftechnologyropar", "indianinstituteoftechnologyroper", "indianinstituteoftechnologyindore", "indianinstituteoftechnologymandi", "indianinstituteoftechnologypalakkad", "indianinstituteoftechnologypalakad", "indianinstituteoftechnologytirupati", "indianinstituteoftechnologydhanbad", "indianinstituteoftechnologybhilai", "indianinstituteoftechnologygoa", "indianinstituteoftechnologyjammu", "indianinstituteoftechnologyjammuandkashmir", "indianinstituteoftechnologydharwad", "indianinstituteoftechnologydharvad");


?>